### ISSUE TITLE
关于构建

### ISSUE THREAD

**Issue by fkajerry** [ArcherGu/archergu#2]
I use `fast-vite-electron`, and enable `nodeIntegration: true`.

When i use `chokidar` to watch files' change, I found native node.js module, such as `fs`, `path` was wrapper as esm, i cause error: 
```
Uncaught TypeError: promisify is not a function
    at node_modules/readdirp/index.js (index.js:9)
    at __require2 (chunk-ZNTI3VZZ.js?v=d533faec:48)
    at node_modules/chokidar/index.js (index.js:7)
    at __require2 (chunk-ZNTI3VZZ.js?v=d533faec:48)
    at dep:chokidar:1
```

and I debug it, found:
![image](https://user-images.githubusercontent.com/3888884/138055380-cabd134a-fe5d-4ed7-b153-08a041e7650a.png)

all the nodejs native modules can't work well

**Comment by ArcherGu** [comment]
Hi, @hermaproditus, thank you for your attention, but I'm sorry, this repository only accepts some questions about me personally.

Please submit issue under [here](https://github.com/ArcherGu/fast-vite-electron/issues). 

I'll track it in the corresponding repository
